name: modular_flutter
packages:
  - apps/*
  - packages/core/**
  - packages/features/**

command:
  bootstrap:
    environment:
      sdk: ^3.8.1
      flutter: ">=1.17.0"

    dependencies:
      dio: ^5.0.0

    dev_dependencies:
      flutter_lints: ^6.0.0