name: modular_flutter
packages:
  - apps/*
  - packages/core/**
  - packages/features/**

command:
  bootstrap:
    environment:
      sdk: ^3.8.1
      flutter: ">=1.17.0"

    dependencies:
      dio: ^5.0.0
      get_it: ^8.0.3
      json_annotation: ^4.9.0


    dev_dependencies:
      flutter_lints: ^6.0.0
      injectable_generator: ^2.0.0
      build_runner: ^2.0.0
      json_serializable: ^6.10.0




scripts:
  bootstrap:
    run: melos bootstrap
  test:
    run: melos exec --concurrency=1 -- flutter test
  format:
    run: melos run format
  analyze:
    run: melos run analyze
  clean:
    run: melos clean