name: modular_flutter
description: "A production-grade Flutter app demonstrating clean architecture, multi-modular design, BLoC state management, and Melos monorepo configuration — based on the Flutter Advanced Course: Multi-Modular & Clean Architecture."
version: 1.0.0+1
publish_to: none # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  melos: ^6.3.3 
  get_it: ^8.0.3
  injectable: ^2.5.1
  app_settings:
    path: packages/features/settings/app_settings

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  injectable_generator: ^2.0.0
  build_runner: ^2.0.0


flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #